-- ==========================================================
-- FILE: 02_create_tables.sql
-- ==========================================================

-- 1. REGIONS (Lookup)
CREATE TABLE regions (
    region_id   NUMBER(5) CONSTRAINT pk_regions PRIMARY KEY,
    region_name VARCHAR2(50) NOT NULL CONSTRAINT uq_region_name UNIQUE
);

-- 2. COUNTRIES (Parent)
CREATE TABLE countries (
    country_id    NUMBER(5) CONSTRAINT pk_countries PRIMARY KEY,
    region_id     NUMBER(5) CONSTRAINT fk_cntry_region REFERENCES regions(region_id),
    country_name  VARCHAR2(50) NOT NULL CONSTRAINT uq_country_name UNIQUE,
    currency_code CHAR(3)
);

-- 3. INDICATORS (Parent)
CREATE TABLE indicators (
    ind_id       NUMBER(5) CONSTRAINT pk_indicators PRIMARY KEY,
    ind_name     VARCHAR2(100) NOT NULL,
    category     VARCHAR2(20) CHECK (category IN ('ECONOMIC', 'RISK', 'TRADE')),
    weight       NUMBER(3,2) CHECK (weight BETWEEN 0 AND 1),
    measure_unit VARCHAR2(20)
);

-- 4. MARKET_DATA (Fact Table)
CREATE TABLE market_data (
    data_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_market_data PRIMARY KEY,
    country_id NUMBER(5) NOT NULL CONSTRAINT fk_data_country REFERENCES countries(country_id),
    ind_id     NUMBER(5) NOT NULL CONSTRAINT fk_data_ind REFERENCES indicators(ind_id),
    data_year  NUMBER(4) CHECK (data_year > 1900),
    data_value NUMBER(15,2) NOT NULL,
    CONSTRAINT uq_market_data UNIQUE (country_id, ind_id, data_year)
);

-- 5. AUDIT_LOG (Security)
CREATE TABLE audit_log (
    log_id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_audit_log PRIMARY KEY,
    db_user        VARCHAR2(30),
    action_type    VARCHAR2(20),
    table_affected VARCHAR2(30),
    log_time       TIMESTAMP DEFAULT SYSTIMESTAMP,
    comments       VARCHAR2(255)
);

-- 6. PUBLIC_HOLIDAYS (Security Support)
CREATE TABLE public_holidays (
    holiday_date DATE CONSTRAINT pk_holidays PRIMARY KEY,
    description  VARCHAR2(50)
);
